# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-10-01 23:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduled_job_manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='datetime_last_updated',
            field=models.DateTimeField(null=True),
        ),
    ]
