# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-10-02 19:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduled_job_manager', '0002_member_datetime_last_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='unavailable',
            field=models.NullBooleanField(),
        ),
    ]
