# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-10-02 22:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduled_job_manager', '0003_task_unavailable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='progress',
        ),
    ]
