# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-10-02 22:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduled_job_manager', '0004_remove_job_progress'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='progress',
            field=models.SmallIntegerField(null=True),
        ),
    ]
